%% Calibraz schermo

% User defined parameters
screen_name = 'AsusSmall_NewCalib2024';
screen_width = 34.4; %cm
screen_height = 19.4; %cm
notes = '?'; % note screen settings. they might affect the luminance output

range = [0 0.9]; % fit using values within range limits. To use all values, use range = [0,1];


tab = []; % paste values into the variable 'tab'. Your data must have 2 or
% 3 columns:
%   - column 1: input values in 0-1 range 
%   - column 2: measured luminance in cd/m2
%   - column 3: measured luminance in cd/m2 using only blue values (optional)

%% 
[~,ord] = sort(tab(:,1));
y2 = tab(ord,:);
vals = round(y2(:,1)*255)./255;
lumi = y2(:,2);
% clear ord tab y2

% [params,f] = fit_screen(vals,gray,'gamma+gauss',range);

% fcn = @(param,x) ( param(1) + param(2).* x.^(param(3)) + param(4).* exp( -(x-param(5)).^2 ./ (param(6).^2) ) );
% [params,f] = fit_screen(vals,gray,fcn,...
%     'LowerValues', [0 0 0 0 0 0],...
%     'UpperValues', [1 inf inf inf 1 1],...
%     'StartValues', [0 gray(1) 1 5 0.4 0.2]);
[params,f] = fit_screen( vals, lumi, 'gamma',...
    'range',        range, ...
    'LowerValues',  [0 0 0 ],...
    'UpperValues',  [lumi(1)*0.9 inf inf],...
    'StartValues',  [lumi(1)*1.1 lumi(end) 1]);
% [params,f] = fit_screen( vals, lumi, 'gamma+gauss',...
%     'range',        range, ...
%     'LowerValues',  [0 0 0 0 0 0],...
%     'UpperValues',  [1 inf inf inf 1 1],...
%     'StartValues',  [lumi(1) lumi(end) 1 mean(lumi) 0.5 0.2]);

if size(tab,2)==3
%     lumi_blue = y2(:,3);
%     [params_blue,f_blue] = fit_screen( vals, lumi_blue, 'gamma+gauss',...
%         'range',        range, ...
%         'LowerValues',  [0 0 0 0 0 0],...
%         'UpperValues',  [1 inf inf inf 1 1],...
%         'StartValues',  [0 lumi_blue(end) 1 mean(lumi_blue) 0.5 0.2]);
    lumi_blue = y2(:,3);
    [params_blue,f_blue] = fit_screen( vals, lumi_blue, 'gamma',...
        'range',        range, ...
        'LowerValues',  [0 0 0],...
        'UpperValues',  [lumi(1)*0.9 inf inf],...
        'StartValues',  [lumi(1)*1.1 lumi_blue(end) 1]);
end

t = table('size',[1 6],...
    'variabletype', {'string', 'double', 'double', 'string',  'string',  'string'},...
    'VariableNames',{'name',   'width',   'height', 'formula', 'formula_blue', 'notes'});
t.name      = screen_name;
t.width     = screen_width;
t.height    = screen_height;
t.formula   = f;
t.formula_blue = f_blue;
t.notes     = notes;
writetable(t,strcat(screen_name,'.dat'))
