t = table('size',[1 6],...
    'variabletype', {'string', 'double', 'double', 'string',  'string',  'string'},...
    'VariableNames',{'name',   'width',   'height', 'formula', 'formula_blue', 'notes'});
